name: NLICM
favicon: null
layout_spectrum: 0.0923
typography_spectrum: 0.85662
title: New Life In Christ Ministries
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d9241b'
    - '#000000'
    - '#e47523'
    - '#bbb8b7'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
