name: NLICM
favicon: null
layout_spectrum: 0.25365
typography_spectrum: 0.54837
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d9241b'
    - '#000000'
    - '#e47523'
    - '#bbb8b7'
  brandStrength: 0.9375
  lightness: 0.875
  saturation: 0.0625
  rhythmicContrast: 0.6513258521445096
purpose: []
